exports.technology = [
  {
    id: 1,
    name: "Python3",
    img: "/images/technology/python.png",
    width: 80,
    height: 80,
  },
  {
    id: 2,
    name: "Numpy",
    img: "/images/technology/numpy.png",
    width: 80,
    height: 80,
  },
  {
    id: 3,
    name: "Pandas",
    img: "/images/technology/pandas.png",
    width: 80,
    height: 80,
  },
  {
    id: 4,
    name: "Tensorflow",
    img: "/images/technology/tensorflow.png",
    width: 80,
    height: 80,
  },
  {
    id: 5,
    name: "Google Colab",
    img: "/images/technology/python_note.png",
    width: 80,
    height: 80,
  },
  {
    id: 6,
    name: "Matplotlib",
    img: "/images/technology/matplotlib.png",
    width: 120,
    height: 80,
  },
  {
    id: 7,
    name: "ScikitLearn",
    img: "/images/technology/scikitlearn.png",
    width: 80,
    height: 80,
  },
  {
    id: 8,
    name: "Darknet",
    img: "/images/technology/darknet.png",
    width: 80,
    height: 80,
  },
  {
    id: 9,
    name: "Yolo v4",
    img: "/images/technology/yolov4.png",
    width: 80,
    height: 80,
  },
  {
    id: 10,
    name: "OpenCV",
    img: "/images/technology/opencv.png",
    width: 80,
    height: 80,
  },
];
